### ISSUE TITLE
Bug: unexpected sed invalid command code M

### ISSUE THREAD

**Issue by lcn2** [xexyl/sgit#1]
When running a command as simple as:

```sh
$ sgit -e 's/foo/bar/g' Makefile
```

The result is an error:

```
sed: 1: "Makefile": invalid command code M
```

Consider however:

```sh
$ sgit -e 's/foo/bar/g' -n -v 1 Makefile
```

This produces:

```
/usr/bin/sed -i -e s/foo/bar/g Makefile
```

And when you run that command directly in the shell:

```
/usr/bin/sed -i -e s/foo/bar/g Makefile
```

The command works.  So while the `-n -v 1' prints what seems to be valid commands, the `sgit(1)` code appears to not execute them properly, producing sed errors.

**Comment by xexyl** [comment]
Thank you Landon! I will look at this soon. 

Of course if you want to take a tackle at it it (so that I can work on the other repo) you're welcome to but maybe this will be obvious. 

Btw: a tip is the `-x` option to turn on tracing (as in shell `-x`) and that is probably what I will have to do. 

Anyway booting up laptop now as I can't sleep so I will look for this soon I hope!

**Comment by xexyl** [comment]
It is what I thought: the version of sed. So macOS `sed(1)` has this problem. I have to use `-s /usr/bin/sed` to test it but that's okay. Hopefully I can work this out relatively easily .... will look at this soon and hopefully have some answers ..

**Comment by xexyl** [comment]
I've discovered the problem. Now for figuring out a fix that won't break the functionality ... the problem btw is it quotes the `-e` followed by the command as one quote. So _hopefully_ one can not have to quote it all.

**Comment by xexyl** [comment]
Might have fixed it: just have to test multiple commands.

**Comment by xexyl** [comment]
It is as I feared: with more than one command it does not work .. still progress.

**Comment by xexyl** [comment]
The problem is the quoting the `-e` for the full array. I have to think of a way to do it so that one can chain commands now.

Running the raw command that is being run by the script works but not in the script.

However I must try and rest now. I will think about it as I am resting. I'll show you more information when I'm back. I have had another idea about it but I need to rest first.

**Comment by xexyl** [comment]
What's curious is I get it to work, it seems, but then the error still shows up .. will look at it again once I've rested which I'm really going to do now.

Thanks for the report!

**Comment by xexyl** [comment]
.. fixed it. Will do a commit shortly and you can test it and then close it if it works as expected!

**Comment by xexyl** [comment]
I have to update documentation to show the output but I'll do the commit to fix the code and then I can look at documentation later .. or maybe I'll just do it quickly. Hmm .. well by the time you're awake it should hopefully be in. I think I'll just do it now as it'll annoy me otherwise.

**Comment by xexyl** [comment]
This bug report helped me uncover some other bugs too .. though it might not be that it'll all be remembered in the log. I have to go do a couple things (might take 15 or more minutes, shouldn't take more than half an hour I hope) and then I'll do a commit. Then if all is good you can close this.

Thank you very much for helping improving this even more! I really appreciate it my friend.

**Comment by xexyl** [comment]
Please see commit df43da2e9018998114ba80d50088b76b2e34d142. Does that resolve it?

Thanks .. going to try resting now. I hope to work on the IOCCC repo later on today but it's a busy day and I've been awake since stupid o'clock once again so who knows. I know what I'd like to work on there but not sure if I'll have the energy. Anyway hopefully this is resolved.

**Comment by lcn2** [comment]
This issue has been fixed.

**Comment by xexyl** [comment]
> This issue has been fixed.

Thank you for confirming it and for helping make it an even better tool! 

Glad you find the tool so useful as you do. I've certainly used it a lot as well.
